"""LLM prompt templates for the evaluator agent.

All prompts used by the agent nodes are defined in per-task-type modules
and re-exported here for convenient ``from src.prompts import ...`` usage.
"""

from src.prompts.coding import (
    CODING_ANALYSIS_SYSTEM_PROMPT,
    CODING_IMPROVEMENT_GUIDANCE,
    CODING_OUTPUT_EVALUATION_SYSTEM_PROMPT,
)
from src.prompts.email import (
    EMAIL_ANALYSIS_SYSTEM_PROMPT,
    EMAIL_IMPROVEMENT_GUIDANCE,
    EMAIL_OUTPUT_EVALUATION_SYSTEM_PROMPT,
)
from src.prompts.exam import (
    EXAM_ANALYSIS_SYSTEM_PROMPT,
    EXAM_IMPROVEMENT_GUIDANCE,
    EXAM_OUTPUT_EVALUATION_SYSTEM_PROMPT,
)
from src.prompts.general import (
    ANALYSIS_SYSTEM_PROMPT,
    FOLLOWUP_SYSTEM_PROMPT,
    IMPROVEMENT_SYSTEM_PROMPT,
    OUTPUT_EVALUATION_SYSTEM_PROMPT,
    PROMPT_TYPE_CONTINUATION,
    PROMPT_TYPE_INITIAL,
    SYSTEM_PROMPT_ANALYSIS_TEMPLATE,
)
from src.prompts.linkedin import (
    LINKEDIN_ANALYSIS_SYSTEM_PROMPT,
    LINKEDIN_IMPROVEMENT_GUIDANCE,
    LINKEDIN_OUTPUT_EVALUATION_SYSTEM_PROMPT,
)
from src.prompts.summarization import (
    SUMMARIZATION_ANALYSIS_SYSTEM_PROMPT,
    SUMMARIZATION_IMPROVEMENT_GUIDANCE,
    SUMMARIZATION_OUTPUT_EVALUATION_SYSTEM_PROMPT,
)

__all__ = [
    "ANALYSIS_SYSTEM_PROMPT",
    "CODING_ANALYSIS_SYSTEM_PROMPT",
    "CODING_IMPROVEMENT_GUIDANCE",
    "CODING_OUTPUT_EVALUATION_SYSTEM_PROMPT",
    "EMAIL_ANALYSIS_SYSTEM_PROMPT",
    "EMAIL_IMPROVEMENT_GUIDANCE",
    "EMAIL_OUTPUT_EVALUATION_SYSTEM_PROMPT",
    "EXAM_ANALYSIS_SYSTEM_PROMPT",
    "EXAM_IMPROVEMENT_GUIDANCE",
    "EXAM_OUTPUT_EVALUATION_SYSTEM_PROMPT",
    "FOLLOWUP_SYSTEM_PROMPT",
    "IMPROVEMENT_SYSTEM_PROMPT",
    "LINKEDIN_ANALYSIS_SYSTEM_PROMPT",
    "LINKEDIN_IMPROVEMENT_GUIDANCE",
    "LINKEDIN_OUTPUT_EVALUATION_SYSTEM_PROMPT",
    "OUTPUT_EVALUATION_SYSTEM_PROMPT",
    "PROMPT_TYPE_CONTINUATION",
    "PROMPT_TYPE_INITIAL",
    "SUMMARIZATION_ANALYSIS_SYSTEM_PROMPT",
    "SUMMARIZATION_IMPROVEMENT_GUIDANCE",
    "SUMMARIZATION_OUTPUT_EVALUATION_SYSTEM_PROMPT",
    "SYSTEM_PROMPT_ANALYSIS_TEMPLATE",
]
